apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: secure-sample-app

resources:
  - ../../base

images:
  - name: secure-sample-app
    newName: ghcr.io/example-org/secure-sample-app
    newTag: "main" # Updated automatically by CI pipeline

commonLabels:
  app.kubernetes.io/managed-by: kustomize
  environment: production

replicas:
  - name: secure-sample-app
    count: 3
